add to google calendar with gcalcli, skip saving events less than 1 minute, etc

diff --git a/potime b/potime
--- a/potime
+++ b/potime
@@ -6,6 +6,7 @@ thisdir="$( cd "$( dirname "$( realpath "${BASH_SOURCE[0]}" )" )" && pwd )"
 PATH=${PATH}:${thisdir}
 
 [[ -z "${TIMECLOCKFILE}" ]] && timeclockfile=~/${USER}.timeclock || timeclockfile="${TIMECLOCKFILE}"
+[[ -z "${GCALENDARNAME}" ]] && gcalendarname="UNSPECIFIED" || gcalendarname="${GCALENDARNAME}"
 
 # If an alarm.mp3 exists we'll try to use it... easy to drop in without messing with env
 #FIXME: tidy this up, break out a function for the sound playback...
@@ -23,11 +24,12 @@ fi
 function helpmsg() {
 	echo -e "\n"
 	echo "         USAGE:  potime [minutes] [account:optionalsubaccount] [optional description]"
-	echo "      EXAMPLES:  potime 25 POISM:DEV timeclocker"
-	echo "   ENVIRONMENT:  export TIMECLOCKFILE=~/yourusername.timeclock"
+	echo "      EXAMPLES:  potime 25 POISM:DEV potime app"
+	echo '   ENVIRONMENT:  export TIMECLOCKFILE=~/yourusername.timeclock; export GCALENDARNAME="TimeClock"'
 	echo "CURRENT CONFIG:"
 	echo "                 TIMECLOCKFILE: ${timeclockfile}"
 	echo "                 TIMECLOCKSOUND: ${timeclocksound}"
+	echo "                 GCALENDARNAME: ${gcalcalendarname}"
 	echo -e "\n"
 }
 
@@ -94,7 +96,7 @@ function runtimer() {
 	echo "FILE: ${timeclockfile}"
 	echo "TIME: ${maxminutes} minutes, starting at $(date +'%r')"
 	if [ ${totalminutes} -gt ${maxminutes} ]; then
-		echo "EXTEND: Task extended ${totalminutes} minutes. Originally was ${originalminutes} minutes, starting at ${starttimesimple}"
+		echo "EXTEND: Task extended to ${totalminutes} minutes. Originally was ${originalminutes} minutes, starting at ${starttimesimple}"
 	fi
 	echo "TASK: ${task}"
 	progress ${maxseconds}
@@ -152,10 +154,35 @@ function runtimer() {
 	done
 }
 
+function addtogooglecalendar() {
+	#addtogooglecalendar "${account}" "${descriptionclean}\n${commentsclean}" "${starttime}" "${clockminonly}"
+	#gcalcli add --title="POISM:dev" --description="OK this is a description passed from cli..." --when="2024-01-25 15:00:00" --duration=30
+	if [ "${gcalendarname}" == "UNSPECIFIED" ]; then
+		gcalcli add --title="${1}" --description="${2}" --when="${3}" --duration="${4}" --noprompt
+	else
+		gcalcli add --calendar="${gcalendarname}" --title="${1}" --description="${2}" --when="${3}" --duration="${4}" --noprompt
+	fi
+
+
+	if [ $? -eq 0 ]; then
+		echo "OK: Added to google calendar ${gcalendarname}"
+	else
+		echo "ERROR: Failed to add to google calendar ${gcalendarname}"
+		echo 'Please check your gcalcli auth and define --default-calendar="Your Calendar Name" to ~/.gcalccli or specify by export GCALENDARNAME="Your Calendar Name" before running this script.'
+	fi
+}
+
 function clockout() {
 	interrupted=1
-	endtime=$(date "+%Y/%m/%d %H:%M:%S")
+	if [ "$SECONDS" -lt "60" ]; then
+		echo -e "\n"
+		echo -e "${hrule}"
+		echo "WARNING: Duration less than 1 minute, not worth reporting. Exiting timer."
+		echo -e "${hrule}"
+		exit
+	fi
 	duration=$SECONDS
+	endtime=$(date "+%Y/%m/%d %H:%M:%S")
 	clockhrs=$(( ${duration} / 3600 ))
 	clockmin=$(( ${duration} % 3600 / 60))
 	clockminonly=$(( ${duration} / 60))
@@ -196,6 +223,16 @@ function clockout() {
 		echo "o $endtime" >> "${timeclockfile}"
 		echo -e "${hrule}"
 		tail -n 2 "${timeclockfile}"
+
+		if command -v gcalcli &> /dev/null; then
+			echo -e "${hrule}"
+			echo "Add to ${gcalendarname} google calendar?"
+			if confirm; then
+				addtogooglecalendar "${account}" "${descriptionclean} ; ${commentsclean}" "${starttime}" "${clockminonly}"
+			fi
+		fi
+
+
 		if ! command -v hledger &> /dev/null; then
 			echo "WARNING: hledger not installed, cannot check balances."
 			echo "Do you wish to install hledger?"
